language: node_js
node_js:
    - "7"
cache:
  directories:
    - node_modules

before_install:
    - echo '{"accountKey":"key"}' > config.json

script: 
    - npm test

after_script:
    - npm run cover
    - cat ./coverage/lcov.info | coveralls
